name: Pull request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality_check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test -- --coverage
      - name: Check code style
        run: npm run lint
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
